before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: oshka-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/oshka.version={{.Version}} -X github.com/k1LoW/oshka.commit={{.FullCommit}} -X github.com/k1LoW/oshka.date={{.Date}} -X github.com/k1LoW/oshka/version.Version={{.Version}}
-
  id: oshka-darwin-windows
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/oshka.version={{.Version}} -X github.com/k1LoW/oshka.commit={{.FullCommit}} -X github.com/k1LoW/oshka.date={{.Date}} -X github.com/k1LoW/oshka/version.Version={{.Version}}
-
  id: oshka-darwin-arm64
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/oshka.version={{.Version}} -X github.com/k1LoW/oshka.commit={{.FullCommit}} -X github.com/k1LoW/oshka.date={{.Date}} -X github.com/k1LoW/oshka/version.Version={{.Version}}    
archives:
-
  id: oshka-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/k1low/oshka:v{{ .Version }}'
      - 'ghcr.io/k1low/oshka:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/k1LoW/oshka"
    extra_files:
      - scripts/entrypoint.sh
brews:
  -
    name: oshka
    tap:
      owner: k1LoW
      name: homebrew-tap
    commit_author:
      name: k1LoW
      email: k1lowxb@gmail.com
    homepage: https://github.com/k1LoW/oshka
    description: oshka is a tool for extracting nested CI/CD supply chains and executing commands.
    license: MIT
nfpms:
  - id: oshka-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - oshka-linux
    homepage: https://github.com/k1LoW/oshka
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: oshka is a tool for extracting nested CI/CD supply chains and executing commands.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
